# Generated by Django 5.2.17 on 2026-09-09 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shopee', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('url_shopee', models.URLField(blank=True, max_length=500, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.store')),
            ],
        ),
    ]
