# Generated by Django 5.2.17 on 2026-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_shopee',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
