# Generated by Django 5.2.17 on 2026-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_url_shopee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_shopee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
