# Generated by Django 5.2.17 on 2026-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
