# Generated by Django 5.2.17 on 2026-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
